site_name: Polytoria Docs
copyright: Copyright &copy; 2019 - 2026 Polytoria - <a href="/contributors" class="contributors-link-footer">brought to you by &lt3</a>

theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.instant
    - navigation.path
    - content.code.annotate
    - content.code.copy
    - navigation.top
    - toc.follow

  name: material
  custom_dir: docs/theme
  logo: assets/logo # Not a problem, it auto selects from the logo-dark and logo-light automaticly
  favicon: assets/logo-dark.svg

  font:
    text: Rubik

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: dark
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to light mode

  icon:
    menu: fontawesome/solid/bars
    previous: fontawesome/solid/angle-left
    alternate: fontawesome/solid/globe
    search: fontawesome/solid/search
    share: fontawesome/solid/share
    close: fontawesome/solid/x
    top: fontawesome/solid/chevron-up
    edit: fontawesome/solid/pencil
    view: fontawesome/solid/code
    repo: fontawesome/solid/box-archive
    admonition:
      note: fontawesome/solid/pencil
      abstract: fontawesome/solid/brain
      info: fontawesome/solid/info-circle
      tip: fontawesome/solid/fire
      success: fontawesome/solid/check
      question: fontawesome/solid/question
      warning: fontawesome/solid/warning
      failure: fontawesome/solid/x
      danger: fontawesome/solid/bolt-lightning
      bug: fontawesome/solid/bug
      example: fontawesome/solid/book
      quote: fontawesome/solid/quote-right
    next: fontawsome/solid/angle-right

extra:
  generator: true

plugins:
  - search
  - macros

  - mkdocs-nav-weight:
      section_renamed: true
      index_weight: -10
      warning: true
      reverse: false

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - tables
  - admonition
  - attr_list
  - md_in_html

  - toc:
      permalink: true

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs/theme/.icons

extra_css:
  - assets/extra.css
  - assets/style/palette.css
  - assets/style/header.css
  - assets/style/page.css

validation:
  absolute_links: ignore
